### PR TITLE
feat: implement sync manager

### PR DESCRIPTION
**Pull request by maxnowack**
Work in progress. I will update this PR soon with an explanation how the `SyncManager` works and how to use it.
I'm really unsure about the naming and I'm happy to get some feedback on this.
Right now the SyncManager is placed in the `signaldb` package, but I plan to move it to it's own package later on (probably `v1.0.0`).

I would love to get feedback in general on this. Maybe someone has the time to take a quick look at it 🙂 
I've already added [some tests](https://github.com/maxnowack/signaldb/blob/sync/packages/signaldb/src/SyncManager/index.ts), so this might be a good starting point.

### CODE REVIEW

**Comment by Cmacu** [comment]
@maxnowack Happy to look over your changes, thanks.

- I think SyncManager is all right. alternatively SignalSyncManager or CollectionSyncManager could be a small improvement assuming that most application would need a wrapper or already have something similar in place.
- I didn't go deeply in the details, but overall I think it already looks great. I love that you thought about concurrency issues  and added queue and debounce
- Your testing coverage and setup looks great too!

Two things I am wondering about:

- Do you need separate added and modified given that added checks if given item exists. From a backend/sync perspective it's easier and more performant to get a list of modified records since given typestamp than trying to split them on added vs modified. I think removed is fine and makes sense.
- Its could be a good idea to consider scalability and more specifically paginated results. Alternatively some way to flush/commit the current sync changes mid flight. I am not sure how this would work well and need to go through the details in order to provide better suggestions
- Another think worth thinking about is some type of errors buffer that can be stored and managed separately. I agree with you that ultimately the developer would need to decide how to handle such cases by either displaying them to the user or setting up certain reconciliation strategy. However providing the conflicts during push/pull or even better via hook similarly to the persistence.error one could simplify the implementation. And if the conflicts are stored in signalDB than ability to access  them on demand via api would be great.
- Finally I think setting up some error code system and documentation for it could be very helpful. Maybe you can even index the errors and pipe them in the docs.

It's amazing how quickly you were able to come up with this solution and how clean, well written and easy to read your code is! I will do another take when I get the chance and might add some more specific and code related comments.

**Comment by maxnowack** [comment]
Thanks for your detailed feedback @Cmacu!

> * I think SyncManager is all right. alternatively SignalSyncManager or CollectionSyncManager could be a small improvement assuming that most application would need a wrapper or already have something similar in place.

Okay, let's leave it as it is for now. If someone has a name conflict, it's possible to change the name during import.

> * I didn't go deeply in the details, but overall I think it already looks great. I love that you thought about concurrency issues  and added queue and debounce

Thanks! The idea is to keep the DX as high as possible, to make the implementation of the `SyncManager` straight forward. I'm pretty sure that everyone would implement a queue and debouncing at some point, so why not include it directly. Maybe the debounce delay should be configurable, but I think for now it's fine at 100ms.

> * Do you need separate added and modified given that added checks if given item exists. From a backend/sync perspective it's easier and more performant to get a list of modified records since given typestamp than trying to split them on added vs modified. I think removed is fine and makes sense.

Do you mean during pull/onChange or during push? I'm syncing against a REST API in my project, so I need to distinguish between added and modified documents. I understand that there are other use cases where it would make more sense to keep them together. Maybe we could do an upsert instead of an update. I want to leave the added there so that it is consistent with other places in the code.

> * It could be a good idea to consider scalability and more specifically paginated results. Alternatively maybe a way to flush/commit the current sync changes mid flight. I am not sure how this would work and need to go through the details in order to provide better suggestions.

I'm not sure what you mean exactly. Maybe that's a use case for the [`AutoFetchCollection`](https://signaldb.js.org/replication/#autofetchcollection). This one still extends the old `ReplicatedCollection`, so it needs a refactoring to integrate with the `SyncManager` instead.

> * Another thing worth thinking about is errors buffer that can be stored and managed separately. I agree with you that ultimately the developer would need to decide how to handle such cases by either displaying them to the user or setting up reconciliation strategy. However providing the conflicts during push/pull or even better via hook similarly to the persistence.error could simplify the integration process. And if the conflicts are stored in signalDB than ability to access  them on demand via api would be great.

It's already on my plate! 😀 I'm not 100% sure yet, what the best approach would be. In general we have several types of errors:
* **HTTP errors (`4xx` and `5xx` status codes)**: During `pull` they should let the sync fail, so that no data is saved to local in an error case. During `push` they should be caught and not let the sync fail, that the changes are rolled back with the next `pull`. However, the user want to be notified about an error anyway.
* **Network errors (timeouts, no connection, etc.)**: They should always let the sync fail.
* **Unexpected errors**: errors that happen during `push`, `pull` or internally in the `SyncManager` should also let the sync fail so that they could handled elsewhere.

We also have to think about how errors should be handled that happen during a debounced sync that is triggered by and data modification (insert/update/delete). We also could consider to implement automatic retrying or time scheduled synchronization in cases where it isn't possible to get notified about changes directly. Errors must also be handled async in these cases.

> * Finally I think setting up some error code system and documentation for it could be very helpful. Maybe you can index the errors codes and pipe them in the docs.

I totally agree. I think writing a good documentation for the feature is the most important part. I'll start in the next days.
 
> It's amazing how quickly you were able to come up with this solution and how clean, well written and easy to read your code is! I will do another take when I get the chance and might add more specific and code related comments.

Thank you so much!

**Comment by beorn** [comment]
So AutoFetchCollection is not deprecated, but just needs to be refactored on top of SyncManager?  (The docs reads as if it's deprecated.)

**Comment by maxnowack** [comment]
@beorn yes, the current `AutoFetchCollection` is deprecated. I'm not sure yet if I just refactor it using the `SyncManager` or maybe come up with a totally new approach

**Pull request merged**
