### PR TITLE
add opfs persistence adapter

### PR DESCRIPTION
**Pull request by jamesgibson14**
I don't use TypeScript but this adapter code is working in my system and gives a great base level for using OPFS to persist collections. 
This uses OPFS on the main thread, so I'll probaly play around with using a worker as well.

### CODE REVIEW

**Review by jamesgibson14 — COMMENTED** [review]
This is the first time I've actually used either OPFS and SignalDB, I am learning them both, so any suggestions are welcome.

**Comment by jamesgibson14** [comment]
I'll take another stab at it.

**Review by jamesgibson14 — COMMENTED** [review]
I tried to copy the localStorage tests but I get the error:
`TypeError: Cannot read properties of undefined (reading 'getDirectory')` from `navigator.storage.getDirectory()`

**Comment by maxnowack** [comment]
I seems like `happy-dom` (which is used for mocking the browser environment during the tests) doesn't support `navigator.storage` 🙁 
You could try to implement a very basic mocking for it to make the tests pass. See https://vitest.dev/guide/mocking.html#globals
Please let me know if I could assist you with that 🙂

**Comment by jamesgibson14** [comment]
@maxnowack yes, I might need your help on creating the mock for `navigator.storage`

**Comment by maxnowack** [comment]
I've just added a very simple stub of `navigator.storage`. It seems the tests are still failing, but maybe you want to give it a try 🙂

**Review by maxnowack — APPROVED** [review]

**Comment by maxnowack** [comment]
Released in `v0.11.0` 🎉

**Pull request merged**
